language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codeclimate-test-reporter
script:
  - mkdir -p tmp
  - coverage run --source=generate.py generate.py -l DEBUG -c conf.yaml tmp
after_success:
  - codeclimate-test-reporter

